/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POA.Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class vis_poa_actividad extends javax.swing.JInternalFrame {

    /**
     * Creates new form vis_poa_actividad
     */
    public vis_poa_actividad() {
        initComponents();
    }

    public JLabel getLbl_id() {
        return lbl_id;
    }

    public void setLbl_id(JLabel lbl_id) {
        this.lbl_id = lbl_id;
    }
    

    public JButton getBtnimprimir() {
        return btnimprimir;
    }

    public void setBtnimprimir(JButton btnimprimir) {
        this.btnimprimir = btnimprimir;
    }
    
    

    public JButton getBtneliminar() {
        return btneliminar;
    }

    public void setBtneliminar(JButton btneliminar) {
        this.btneliminar = btneliminar;
    }

    public JButton getBtnguardar() {
        return btnguardar;
    }

    public void setBtnguardar(JButton btnguardar) {
        this.btnguardar = btnguardar;
    }

    public JButton getBtnmodificar() {
        return btnmodificar;
    }

    public void setBtnmodificar(JButton btnmodificar) {
        this.btnmodificar = btnmodificar;
    }

    public JButton getBtnnuevo() {
        return btnnuevo;
    }

    public void setBtnnuevo(JButton btnnuevo) {
        this.btnnuevo = btnnuevo;
    }

    public JComboBox<String> getCombo_objetivo_operativo() {
        return combo_objetivo_operativo;
    }

    public void setCombo_objetivo_operativo(JComboBox<String> combo_objetivo_operarivo) {
        this.combo_objetivo_operativo = combo_objetivo_operarivo;
    }

    public JComboBox<String> getCombo_responsable() {
        return combo_responsable;
    }

    public void setCombo_responsable(JComboBox<String> combo_responsable) {
        this.combo_responsable = combo_responsable;
    }

    public JLabel getLblaniopoa() {
        return lblaniopoa;
    }

    public void setLblaniopoa(JLabel lblaniopoa) {
        this.lblaniopoa = lblaniopoa;
    }

    public JLabel getLblproyecto() {
        return lblproyecto;
    }

    public void setLblproyecto(JLabel lblproyecto) {
        this.lblproyecto = lblproyecto;
    }

    

    public JComboBox<String> getComborecursos() {
        return comborecursos;
    }

    public void setComborecursos(JComboBox<String> comborecursos) {
        this.comborecursos = comborecursos;
    }

    public JDateChooser getFecha_plazo() {
        return fecha_plazo;
    }

    public void setFecha_plazo(JDateChooser fecha_plazo) {
        this.fecha_plazo = fecha_plazo;
    }

    public JTable getTablaactividades() {
        return tablaactividades;
    }

    public void setTablaactividades(JTable tablaactividades) {
        this.tablaactividades = tablaactividades;
    }

    public JTextArea getTxtactividad() {
        return txtactividad;
    }

    public void setTxtactividad(JTextArea txtactividad) {
        this.txtactividad = txtactividad;
    }

    public JTextField getTxtrecursos_financieros() {
        return txtrecursos_financieros;
    }

    public void setTxtrecursos_financieros(JTextField txtrecursos_financieros) {
        this.txtrecursos_financieros = txtrecursos_financieros;
    }

    public JButton getBtnindicador() {
        return btnindicador;
    }

    public void setBtnindicador(JButton btnindicador) {
        this.btnindicador = btnindicador;
    }

    public JButton getBtnregresar() {
        return btnregresar;
    }

    public void setBtnregresar(JButton btnregresar) {
        this.btnregresar = btnregresar;
    }
    
   
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaactividades = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtrecursos_financieros = new javax.swing.JTextField();
        fecha_plazo = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        btneliminar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnmodificar = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        combo_objetivo_operativo = new javax.swing.JComboBox<>();
        combo_responsable = new javax.swing.JComboBox<>();
        comborecursos = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtactividad = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnindicador = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblproyecto = new javax.swing.JLabel();
        lblaniopoa = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnregresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1019, 659));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaactividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Actividad", "Objetivo Operativo", "Actividad", "Responsable", "Plazo", "Recursos financieros"
            }
        ));
        jScrollPane1.setViewportView(tablaactividades);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 530, 350));

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 390, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/buscar (2).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 50, 40));

        jLabel4.setText("Objetivo Operativo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 140, 20));

        jLabel5.setText("Actividad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 80, 20));

        jLabel6.setText("Responsable:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 80, 20));

        jLabel7.setText("Plazo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 60, 20));

        jLabel8.setText("Recursos Financieros:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 110, 20));
        getContentPane().add(txtrecursos_financieros, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, 70, -1));
        getContentPane().add(fecha_plazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 250, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/WhatsApp Image 2022-02-15 at 00.32.29.jpeg"))); // NOI18N
        btneliminar.setBorderPainted(false);
        btneliminar.setContentAreaFilled(false);
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 40, 30));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/guardar.png"))); // NOI18N
        btnguardar.setBorderPainted(false);
        btnguardar.setContentAreaFilled(false);
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 50, 30));

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/nuevo.png"))); // NOI18N
        btnnuevo.setBorderPainted(false);
        btnnuevo.setContentAreaFilled(false);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        jLabel11.setText("Modificar");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 50, -1, -1));

        jLabel12.setText("Eliminar");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 50, 40, -1));

        jLabel13.setText("Guardar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 50, 40, -1));

        jLabel14.setText("Nuevo");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 50, -1, -1));

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/modificar.png"))); // NOI18N
        btnmodificar.setBorderPainted(false);
        btnmodificar.setContentAreaFilled(false);
        jPanel1.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 40, 30));

        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/impresion.png"))); // NOI18N
        btnimprimir.setBorderPainted(false);
        btnimprimir.setContentAreaFilled(false);
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btnimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 40, 30));

        jLabel10.setText("Imprimir");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 410, 80));

        getContentPane().add(combo_objetivo_operativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 250, -1));

        getContentPane().add(combo_responsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 250, -1));

        comborecursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Ista", "Autogestion" }));
        getContentPane().add(comborecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 130, -1));

        txtactividad.setColumns(20);
        txtactividad.setRows(5);
        jScrollPane3.setViewportView(txtactividad);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 250, 80));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("PROYECTO:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 110, 40));

        jLabel18.setText("$");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 10, 20));

        btnindicador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/generarreporte.png"))); // NOI18N
        btnindicador.setText("Añadir Indicador");
        btnindicador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnindicador.setContentAreaFilled(false);
        getContentPane().add(btnindicador, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 150, 40));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1000, 10));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setText("ACTIVIDADES");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 260, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("POA:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 50, 40));

        lblproyecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblproyecto.setText("jLabel1");
        getContentPane().add(lblproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 100, 40));

        lblaniopoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblaniopoa.setText("jLabel1");
        getContentPane().add(lblaniopoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 70, 40));

        lbl_id.setText("---");
        getContentPane().add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 30, -1));

        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 20, -1));

        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/regresar.png"))); // NOI18N
        btnregresar.setBorderPainted(false);
        btnregresar.setContentAreaFilled(false);
        getContentPane().add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 60, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lista Actividades");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/fondo azul (2).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 560, 500));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/instituto.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnimprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnindicador;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnregresar;
    private javax.swing.JComboBox<String> combo_objetivo_operativo;
    private javax.swing.JComboBox<String> combo_responsable;
    private javax.swing.JComboBox<String> comborecursos;
    private com.toedter.calendar.JDateChooser fecha_plazo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lblaniopoa;
    private javax.swing.JLabel lblproyecto;
    private javax.swing.JTable tablaactividades;
    private javax.swing.JTextArea txtactividad;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtrecursos_financieros;
    // End of variables declaration//GEN-END:variables
}
