/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POA.Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author HP
 */
public class vis_poa_proyectos extends javax.swing.JInternalFrame {

    /**
     * Creates new form vis_poa
     */
    public vis_poa_proyectos() {
        initComponents();
    }

    

    public JTable getTabla_lista_proyectos() {
        return Tabla_lista_proyectos;
    }

    public void setTabla_lista_proyectos(JTable Tabla_lista_proyectos) {
        this.Tabla_lista_proyectos = Tabla_lista_proyectos;
    }

    public JTable getTabla_proyecto() {
        return Tabla_proyecto;
    }

    public void setTabla_proyecto(JTable Tabla_proyecto) {
        this.Tabla_proyecto = Tabla_proyecto;
    }

    

    

    public JToggleButton getBtnSiguiente() {
        return btnSiguiente;
    }

    public void setBtnSiguiente(JToggleButton btnSiguiente) {
        this.btnSiguiente = btnSiguiente;
    }

    public JButton getBtn_eliminar() {
        return btn_eliminar;
    }

    public void setBtn_eliminar(JButton btn_eliminar) {
        this.btn_eliminar = btn_eliminar;
    }

    public JToggleButton getBtn_guardar() {
        return btn_guardar;
    }

    public void setBtn_guardar(JToggleButton btn_guardar) {
        this.btn_guardar = btn_guardar;
    }

    public JButton getBtn_modificar() {
        return btn_modificar;
    }

    public void setBtn_modificar(JButton btn_modificar) {
        this.btn_modificar = btn_modificar;
    }

    public JButton getBtn_nuevo() {
        return btn_nuevo;
    }

    public void setBtn_nuevo(JButton btn_nuevo) {
        this.btn_nuevo = btn_nuevo;
    }

    public JTextField getTxt_estrategia() {
        return txt_estrategia;
    }

    public void setTxt_estrategia(JTextField txt_estrategia) {
        this.txt_estrategia = txt_estrategia;
    }

    public JTextField getTxt_obestra() {
        return txt_obestra;
    }

    public void setTxt_obestra(JTextField txt_obestra) {
        this.txt_obestra = txt_obestra;
    }

    public JTextField getTxt_obtac() {
        return txt_obtac;
    }

    public void setTxt_obtac(JTextField txt_obtac) {
        this.txt_obtac = txt_obtac;
    }

    public JTextArea getTxtarea_obopera() {
        return txtarea_obopera;
    }

    public void setTxtarea_obopera(JTextArea txtarea_obopera) {
        this.txtarea_obopera = txtarea_obopera;
    }

    public JTextField getN_proyectos() {
        return n_proyectos;
    }

    public void setN_proyectos(JTextField n_proyectos) {
        this.n_proyectos = n_proyectos;
    }

    public JButton getBtn_imprimir() {
        return btn_imprimir;
    }

    public void setBtn_imprimir(JButton btn_imprimir) {
        this.btn_imprimir = btn_imprimir;
    }

    public JToggleButton getBtnAñadir_op() {
        return btnAñadir_op;
    }

    public void setBtnAñadir_op(JToggleButton btnAñadir_op) {
        this.btnAñadir_op = btnAñadir_op;
    }

    public JToggleButton getBtneliminar_op() {
        return btneliminar_op;
    }

    public void setBtneliminar_op(JToggleButton btneliminar_op) {
        this.btneliminar_op = btneliminar_op;
    }

    public JToggleButton getBtnmodificar_op() {
        return btnmodificar_op;
    }

    public void setBtnmodificar_op(JToggleButton btnmodificar_op) {
        this.btnmodificar_op = btnmodificar_op;
    }

    public JLabel getLb_anio() {
        return Lb_anio;
    }

    public void setLb_anio(JLabel Lb_anio) {
        this.Lb_anio = Lb_anio;
    }

    public JLabel getLb_carrera() {
        return Lb_carrera;
    }

    public void setLb_carrera(JLabel Lb_carrera) {
        this.Lb_carrera = Lb_carrera;
    }

    public JLabel getLb_poa() {
        return Lb_poa;
    }

    public void setLb_poa(JLabel Lb_poa) {
        this.Lb_poa = Lb_poa;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel9 = new javax.swing.JLabel();
        txt_obestra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_obtac = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_lista_proyectos = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_estrategia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        n_proyectos = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtarea_obopera = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_proyecto = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btneliminar_op = new javax.swing.JToggleButton();
        btnAñadir_op = new javax.swing.JToggleButton();
        btnmodificar_op = new javax.swing.JToggleButton();
        btn_guardar = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        btn_imprimir = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Lb_anio = new javax.swing.JLabel();
        Lb_poa = new javax.swing.JLabel();
        Lb_carrera = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("OBJETIVO ESTRATÉGICO:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));
        getContentPane().add(txt_obestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 270, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("OBJETIVO TÁCTICO:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));
        getContentPane().add(txt_obtac, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 270, -1));

        Tabla_lista_proyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabla_lista_proyectos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 430, 230));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("CARRERA:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ESTRATEGIA");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));
        getContentPane().add(txt_estrategia, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 270, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PROYECTOS:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Eliminar");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Modificar");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nuevo");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/WhatsApp Image 2022-02-15 at 00.32.29.jpeg"))); // NOI18N
        jPanel2.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 40, 40));

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/modificar.png"))); // NOI18N
        jPanel2.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 50, 40));

        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/nuevo.png"))); // NOI18N
        jPanel2.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 40, 40));
        jPanel2.add(n_proyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 30, -1));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/siguiente.png"))); // NOI18N
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setContentAreaFilled(false);
        jPanel2.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 60, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 270, 50));

        txtarea_obopera.setColumns(20);
        txtarea_obopera.setRows(5);
        jPanel3.add(txtarea_obopera, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 310, 110));

        Tabla_proyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NUMERO", "OBJETIVO "
            }
        ));
        jScrollPane1.setViewportView(Tabla_proyecto);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 490, 90));

        jLabel8.setText("OBJETIVO OPÉRATIVO:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        btneliminar_op.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/delete.jpg"))); // NOI18N
        btneliminar_op.setText("Eliminar");
        btneliminar_op.setBorderPainted(false);
        btneliminar_op.setContentAreaFilled(false);
        btneliminar_op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar_opActionPerformed(evt);
            }
        });
        jPanel3.add(btneliminar_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        btnAñadir_op.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/icono_agregar.png"))); // NOI18N
        btnAñadir_op.setText("Añadir Objetivo");
        btnAñadir_op.setBorderPainted(false);
        btnAñadir_op.setContentAreaFilled(false);
        btnAñadir_op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadir_opActionPerformed(evt);
            }
        });
        jPanel3.add(btnAñadir_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        btnmodificar_op.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/icons8_Report_Card_20px.png"))); // NOI18N
        btnmodificar_op.setText("Modificar");
        btnmodificar_op.setBorderPainted(false);
        btnmodificar_op.setContentAreaFilled(false);
        btnmodificar_op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificar_opActionPerformed(evt);
            }
        });
        jPanel3.add(btnmodificar_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 510, 250));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/guardar.png"))); // NOI18N
        btn_guardar.setBorderPainted(false);
        btn_guardar.setContentAreaFilled(false);
        jPanel2.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 50, 40));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Guardar");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/impresion.png"))); // NOI18N
        jPanel2.add(btn_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 40, 40));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Imprimir");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/fondo azul (2).jpg"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 560, 520));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("LISTA PROYECTOS DEL POA:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("AÑO:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        Lb_anio.setText("jLabel1");
        getContentPane().add(Lb_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 270, -1));

        Lb_poa.setText("jLabel1");
        getContentPane().add(Lb_poa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 270, -1));

        Lb_carrera.setText("jLabel1");
        getContentPane().add(Lb_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 280, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/logo Instituto.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Proyectos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminar_opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar_opActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminar_opActionPerformed

    private void btnAñadir_opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadir_opActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadir_opActionPerformed

    private void btnmodificar_opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificar_opActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificar_opActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lb_anio;
    private javax.swing.JLabel Lb_carrera;
    private javax.swing.JLabel Lb_poa;
    private javax.swing.JTable Tabla_lista_proyectos;
    private javax.swing.JTable Tabla_proyecto;
    private javax.swing.JToggleButton btnAñadir_op;
    private javax.swing.JToggleButton btnSiguiente;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JToggleButton btn_guardar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JToggleButton btneliminar_op;
    private javax.swing.JToggleButton btnmodificar_op;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField n_proyectos;
    private javax.swing.JTextField txt_estrategia;
    private javax.swing.JTextField txt_obestra;
    private javax.swing.JTextField txt_obtac;
    private javax.swing.JTextArea txtarea_obopera;
    // End of variables declaration//GEN-END:variables
}
