/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POA.Vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class vis_Docentes extends javax.swing.JInternalFrame {

    public JButton getBtnimprimir() {
        return btnimprimir;
    }

    public void setBtnimprimir(JButton btnimprimir) {
        this.btnimprimir = btnimprimir;
    }

    
    
    public JButton getBtnmodificar() {
        return btnmodificar;
    }

    public void setBtnmodificar(JButton btnmodificar) {
        this.btnmodificar = btnmodificar;
    }

    
    public JButton getBtncancelar() {
        return btncancelar;
    }

    public void setBtncancelar(JButton btncancelar) {
        this.btncancelar = btncancelar;
    }

    public JButton getBtnguardar() {
        return btnguardar;
    }

    public void setBtnguardar(JButton btnguardar) {
        this.btnguardar = btnguardar;
    }

    public JComboBox<String> getCombo_tiempo() {
        return combo_tiempo;
    }

    public void setCombo_tiempo(JComboBox<String> combo_tiempo) {
        this.combo_tiempo = combo_tiempo;
    }


    public JLabel getLbbtnregistarpersona() {
        return lbbtnregistarpersona;
    }

    public void setLbbtnregistarpersona(JLabel lbbtnregistarpersona) {
        this.lbbtnregistarpersona = lbbtnregistarpersona;
    }

    public JLabel getLbfoto() {
        return lbfoto;
    }

    public void setLbfoto(JLabel lbfoto) {
        this.lbfoto = lbfoto;
    }

    public JLabel getLbnombreycedula() {
        return lbnombreycedula;
    }

    public void setLbnombreycedula(JLabel lbnombreycedula) {
        this.lbnombreycedula = lbnombreycedula;
    }

    public JRadioButton getRbdocentecapacitador() {
        return rbdocentecapacitador;
    }

    public void setRbdocentecapacitador(JRadioButton rbdocentecapacitador) {
        this.rbdocentecapacitador = rbdocentecapacitador;
    }

    public JRadioButton getRbotrotrabajo() {
        return rbotrotrabajo;
    }

    public void setRbotrotrabajo(JRadioButton rbotrotrabajo) {
        this.rbotrotrabajo = rbotrotrabajo;
    }

    public JTable getTabla_docentes() {
        return tabla_docentes;
    }

    public void setTabla_docentes(JTable tabla_docentes) {
        this.tabla_docentes = tabla_docentes;
    }

    public JTextField getTxtabreviatura() {
        return txtabreviatura;
    }

    public void setTxtabreviatura(JTextField txtabreviatura) {
        this.txtabreviatura = txtabreviatura;
    }

    public JTextField getTxtidentificacion() {
        return txtidentificacion;
    }

    public void setTxtidentificacion(JTextField txtidentificacion) {
        this.txtidentificacion = txtidentificacion;
    }

    public JTextField getTxttitulo() {
        return txttitulo;
    }

    public void setTxttitulo(JTextField txttitulo) {
        this.txttitulo = txttitulo;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JButton getBtn_estado() {
        return btn_estado;
    }

    public void setBtn_estado(JButton btn_estado) {
        this.btn_estado = btn_estado;
    }

    public JLabel getVal_persona() {
        return val_persona;
    }

    public void setVal_persona(JLabel val_persona) {
        this.val_persona = val_persona;
    }

    

    
    /**
     * Creates new form vis_Docentes
     */
    public vis_Docentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtidentificacion = new javax.swing.JTextField();
        lbnombreycedula = new javax.swing.JLabel();
        lbbtnregistarpersona = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttitulo = new javax.swing.JTextField();
        txtabreviatura = new javax.swing.JTextField();
        combo_tiempo = new javax.swing.JComboBox<>();
        rbdocentecapacitador = new javax.swing.JRadioButton();
        rbotrotrabajo = new javax.swing.JRadioButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        lbfoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_docentes = new javax.swing.JTable();
        btnmodificar = new javax.swing.JButton();
        btn_estado = new javax.swing.JButton();
        val_persona = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnimprimir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("DOCENTES");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jLabel2.setText("IDENTIFICACION:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtidentificacion.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jPanel1.add(txtidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 182, -1));

        lbnombreycedula.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jPanel1.add(lbnombreycedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 360, 20));

        lbbtnregistarpersona.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 11)); // NOI18N
        lbbtnregistarpersona.setForeground(new java.awt.Color(0, 0, 204));
        lbbtnregistarpersona.setText("REGISTRAR PERSONA");
        jPanel1.add(lbbtnregistarpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 720, 3));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jLabel3.setText("Título del docente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jLabel4.setText("Abreviatura del docente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jLabel5.setText("Tiempo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        txttitulo.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jPanel1.add(txttitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 360, -1));

        txtabreviatura.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jPanel1.add(txtabreviatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 62, -1));

        combo_tiempo.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        combo_tiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE:", "TIEMPO COMPLETO", "MEDIO TIEMPO" }));
        jPanel1.add(combo_tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        buttonGroup1.add(rbdocentecapacitador);
        rbdocentecapacitador.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        rbdocentecapacitador.setText("Docente Capacitador");
        jPanel1.add(rbdocentecapacitador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        buttonGroup1.add(rbotrotrabajo);
        rbotrotrabajo.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        rbotrotrabajo.setText("Otro trabajo");
        jPanel1.add(rbotrotrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/Save-icon (4).png"))); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.setContentAreaFilled(false);
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, 40));

        btncancelar.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/nuevo.png"))); // NOI18N
        btncancelar.setText("NUEVO");
        btncancelar.setContentAreaFilled(false);
        jPanel1.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        lbfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 145, 120));

        tabla_docentes.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        tabla_docentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CEDULA", "TITULO", "ABREVIATURA", "TIEMPO", "OCUPACION", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_docentes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 670, 170));

        btnmodificar.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/modificar.png"))); // NOI18N
        btnmodificar.setText("MODIFICAR");
        btnmodificar.setContentAreaFilled(false);
        jPanel1.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 130, -1));

        btn_estado.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        btn_estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/CAMBIAR ESTADO (1).png"))); // NOI18N
        btn_estado.setText("CAMBIAR ESTADO");
        btn_estado.setContentAreaFilled(false);
        jPanel1.add(btn_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 160, -1));

        val_persona.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(val_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/ISTA.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 300, 70));

        btnimprimir.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/nuevo.png"))); // NOI18N
        btnimprimir.setText("IMPRIMIR");
        btnimprimir.setContentAreaFilled(false);
        jPanel1.add(btnimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_estado;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnmodificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo_tiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbbtnregistarpersona;
    private javax.swing.JLabel lbfoto;
    private javax.swing.JLabel lbnombreycedula;
    private javax.swing.JRadioButton rbdocentecapacitador;
    private javax.swing.JRadioButton rbotrotrabajo;
    private javax.swing.JTable tabla_docentes;
    private javax.swing.JTextField txtabreviatura;
    private javax.swing.JTextField txtidentificacion;
    private javax.swing.JTextField txttitulo;
    private javax.swing.JLabel val_persona;
    // End of variables declaration//GEN-END:variables
}
